- name: Provision Stack
  hosts: localhost
  connection: local

  vars:
    aws_region: eu-central-1
    aws_cf_eksctl_stack_name: "eksctl-{{ lookup('env','USER') }}-k8s-harbor-cluster"
    aws_cf_stack_name: "{{ aws_cf_eksctl_stack_name }}-pgsql"
    aws_cf_db_username: myadmin
    aws_cf_db_password: myadmin_user_password
    aws_pgsql_fqdn: "pgsql.{{ domain }}"
    aws_cf_tags:
      Application: Harbor
      Consumer: "{{ lookup('env','USER') }}"
      DNS: "{{ aws_pgsql_fqdn }}"
      Environment: Test
    domain: mylabs.dev

  tasks:
    - name: Get summary information about a cloudformation stack
      cloudformation_facts:
        stack_name: "{{ aws_cf_eksctl_stack_name }}"

    - name: Create/update stack
      cloudformation:
        region: "{{ aws_region }}"
        stack_name: "{{ aws_cf_stack_name }}"
        state: present
        disable_rollback: true
        template_body: "{{ lookup('template', 'templates/aws_cf_stack-postgresql_db.yml.j2') }}"
        tags: "{{ aws_cf_tags }}"
      register: cloudformation_result

    - name: Create harbor databases in PostgreSQL
      postgresql_db:
        login_host: "{{ aws_pgsql_fqdn }}"
        login_user: "{{ aws_cf_db_username }}"
        login_password: "{{ aws_cf_db_password }}"
        name: "{{ item }}"
      loop:
        - harbor-registry
        - harbor-clair
        - harbor-notary_server
        - harbor-notary_signer

    - name: Create harbor user to access the DBs
      postgresql_user:
        login_host: "{{ aws_pgsql_fqdn }}"
        login_user: "{{ aws_cf_db_username }}"
        login_password: "{{ aws_cf_db_password }}"
        name: "harbor_user"
        password: "harbor_user_password"
        db: postgres
      changed_when: false

    - name: GRANT ALL PRIVILEGES ON DATABASE harbor* TO harbor_user
      postgresql_privs:
        login_host: "{{ aws_pgsql_fqdn }}"
        login_user: "{{ aws_cf_db_username }}"
        login_password: "{{ aws_cf_db_password }}"
        db: postgres
        privs: ALL
        type: database
        obj: "{{ item }}"
        role: harbor_user
      loop:
        - harbor-registry
        - harbor-clair
        - harbor-notary_server
        - harbor-notary_signer
